version: "3.9"

services:
  client:
    build: ./client
    ports:
      - "4173:5173"
    environment:
      - VITE_RELAY_URL=http://localhost:4001
      - VITE_GATEWAY_URL=http://localhost:4002
    depends_on:
      - relay
    volumes:
      - ./client/public:/app/public:rw
      - ./client/src:/app/src:rw
      - ./client/.env:/app/.env:ro
      - ./client/index.html:/app/index.html:rw
      - type: tmpfs
        target: /app/node_modules/.vite
        tmpfs:
          mode: 01777
      - type: tmpfs
        target: /app/node_modules/.vite-temp
        tmpfs:
          mode: 01777

  relay:
    build: ./nginx
    ports:
      - "4001:80"
    depends_on:
      - gateway

  gateway:
    build:
      context: ./privacy-gateway-server-go
      dockerfile: Dockerfile
    ports:
      - "4567:4567"
    environment:
      - LOG_FORMAT=json
      - LOG_LEVEL=DEBUG
      - PORT=4567
      - SEED_SECRET_KEY=869663da4842c8cd5bca96047dd7dd09ff88a9907fd17c9fd585fa219ee987de
    depends_on:
      - target
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:4567/health"]
      interval: 10s
      timeout: 3s
      retries: 5

  target:
    build: ./target
    environment:
      - PORT=4003
    volumes:
      - ./target/src:/app/src
      - ./target/package.json:/app/package.json:rw
    command: ["npm", "run", "dev"]